# Generated by Django 4.0.6 on 2022-07-10 13:55

from django.db import migrations, models
import swimrecords.validator


class Migration(migrations.Migration):

    dependencies = [
        ('swimrecords', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swimrecord',
            name='stroke',
            field=models.CharField(max_length=50, validators=[swimrecords.validator.validate_stroke]),
        ),
    ]
