# Generated by Django 4.0.6 on 2022-07-10 15:18

from django.db import migrations, models
import swimrecords.validator


class Migration(migrations.Migration):

    dependencies = [
        ('swimrecords', '0003_alter_swimrecord_relay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swimrecord',
            name='distance',
            field=models.IntegerField(validators=[swimrecords.validator.min_distance]),
        ),
    ]
