# Generated by Django 4.0.6 on 2022-07-10 15:30

from django.db import migrations, models
import swimrecords.validator


class Migration(migrations.Migration):

    dependencies = [
        ('swimrecords', '0005_alter_swimrecord_record_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swimrecord',
            name='record_broken_date',
            field=models.DateTimeField(validators=[swimrecords.validator.validate_record_date]),
        ),
    ]
